<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>lk.jiat</groupId>
        <artifactId>techmart-ee</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>techmart-ear</artifactId>
    <packaging>ear</packaging>
    <name>techmart-ear</name>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>lk.jiat</groupId>
            <artifactId>techmart-core</artifactId>
            <version>1.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>lk.jiat</groupId>
            <artifactId>techmart-ejb</artifactId>
            <version>1.0</version>
            <type>ejb</type>
        </dependency>
        <dependency>
            <groupId>lk.jiat</groupId>
            <artifactId>techmart-web</artifactId>
            <version>1.0</version>
            <type>war</type>
        </dependency>
    </dependencies>

    <build>
        <finalName>
            ${project.name}
        </finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                    <modules>
                        <webModule>
                            <groupId>lk.jiat</groupId>
                            <artifactId>techmart-web</artifactId>
                            <contextRoot>/techmart-ear</contextRoot>
                        </webModule>
                        <ejbModule>
                            <groupId>lk.jiat</groupId>
                            <artifactId>techmart-ejb</artifactId>
                        </ejbModule>
                    </modules>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>